### ISSUE TITLE
S3 automatically enable block public access

### ISSUE THREAD

**Issue by samkahchiin** [dbl-works/terraform#217]
https://github.com/hashicorp/terraform-provider-aws/issues/31021

https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-s3-automatically-enable-block-public-access-disable-access-control-lists-buckets-april-2023/

result in the s3 bucket creation error

**Comment by swiknaba** [comment]
closed in https://github.com/dbl-works/terraform/pull/224
